# Generated by Django 6.0.7 on 2026-07-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPTRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='url do ppt')),
                ('upload', models.FileField(null=True, upload_to='ppt')),
            ],
        ),
    ]
