# Generated by Django 6.0.7 on 2026-07-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pptroute',
            table='ppt_routes',
        ),
    ]
