# Generated by Django 6.0.7 on 2026-07-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0003_alter_pptroute_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pptroute',
            table='ppt_routes',
        ),
    ]
