# Generated by Django 6.0.7 on 2026-07-18 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt', '0004_alter_pptroute_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pptroute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pptroute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
