services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./app:/app
      - /app/node_modules

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    volumes:
      - ./server:/app
      - venv:/app/.venv
    

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'Dontoffice@2622'
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Express'
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
    driver: local
  venv: