name: Deploy do frontend no Azure Static

on:
  push:
    branches:
      - master
    paths:
      - "app/**"

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths:
      - "app/**"

  workflow_run:
    workflows:
      - Deploy backend no Azure App
    types:
      - completed

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Copiar para .env.production
        working-directory: app
        run: cp .env.prod .env.production

      - name: Instalar dependências
        working-directory: app
        run: npm ci

      - name: Build
        working-directory: app
        run: npm run build

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_SAND_04F0E440F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "./app"
          output_location: "dist"
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest

    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_SAND_04F0E440F }}
          action: close
          app_location: "./app"